### ISSUE TITLE
誤植の報告（コマンド6.3.18）

### ISSUE THREAD

**Issue by katsumata-ryo** [n-takehata/kotlin-server-side-programming-practice#4]
勘違いでしたら申し訳ありません。

誤：`cd kotlin-server-side-programming-practice/part6/front/book-manager`
正：`cd kotlin-server-side-programming-practice/part2/front/book-manager`

**Comment by katsumata-ryo** [comment]
不要な報告だったようなのでcloseします。失礼いたしました。

**Comment by n-takehata** [comment]
@katsumata-ryo 
ご指摘いただきありがとうございます。
こちら確かに間違っており、誤植になります。
現在出版社の方に対応確認中になります。

ご連絡が遅くなってしまい大変申し訳ございません。

**Comment by n-takehata** [comment]
@katsumata-ryo 
こちら正誤表に反映致しました。
ご指摘いただきありがとうございました。

https://gihyo.jp/book/2021/978-4-297-11859-4/support

また、書籍に関しましてもご購入、ご活用いただきありがとうございます。
もしまた不明点やご要望等ございましたら、以下のフォームからご連絡いただければと思います。

https://gihyo.jp/site/inquiry/book?ISBN=978-4-297-11859-4

宜しくお願い致します。
