### ISSUE TITLE
chapter12のREADME.mdに誤字と思しきものがあります。

### ISSUE THREAD

**Issue by kazurof** [n-takehata/kotlin-server-side-programming-practice#6]
以下のファイルにおいて、

`chapter12ディレクトリが、KtorアプリケーションのGradleプロジェクトとなっています。`

とありますが、Kotest とMockK のサンプルなのだろうと思います。

https://github.com/n-takehata/kotlin-server-side-programming-practice/blob/main/part3/chapter12/README.md

**Comment by n-takehata** [comment]
@kazurof 
ご指摘いただきありがとうございます。
こちら誤りでしたので、READMEの方を修正致しました。

**Comment by kazurof** [comment]
確認しました。ありがとうございました。
